language: python
sudo: false

matrix:
    include:
        - python: 2.7
          os: linux
          dist: xenial
          env: TOXENV=py27
        - python: pypy
          os: linux
          dist: xenial
          env: TOXENV=pypy
    allow_failures:
    - python: pypy

install:
  - pip install -r requirements.d/development.txt
  - pip install .

script: tox MoinMoin
